DATASETS:
  # Source - haptik / dialoglue
  DATASET_SOURCE: "haptik"
  # For Haptik - curekart / powerplay11 / sofmattress
  # For Dialogue - banking / clinc / hwu
  DATASET_NAME: "curekart"
  OOS_CLASS_NAME: "NO_NODES_DETECTED"
  # Subsets of train data to use. haptik - "train"/"subset_train", dialoglue - "train"/"train_5"/"train_10"
  DATA_SUBSET: "train"
  N_LABELS: 28

TRAINING:
  # Model - type - CROSS_ENCODER / BI_ENCODER / CLASSIFIER / SBERT_CROSS_ENCODER
  MODEL_TYPE : "SBERT_CROSS_ENCODER"
  NUM_ITERATIONS : 10000
  TRAIN_OUTPUT_DIR: "./models/"
  # Specify the model like "sentence-transformers/all-MiniLM-L6-v2" or "bert-base-uncased" /"cross-encoder/stsb-distilroberta-base"
  MODEL_NAME : "bert-base-uncased"
  TOKENIZER_NAME: "bert-base-uncased"
  # Specify model layer to unfreeze - 11,5 etc
  LAYERS_TO_UNFREEZE : [11]
  # Specify a loss metric for Sentence Bert Bi-Encoder models - CosineSimilarityLoss / ContrastiveLoss
  LOSS_METRIC : "ContrastiveLoss"
  BATCH_SIZE : 16
  LEARNING_RATE: 2e-5
  # Specify scheduler - "WarmupLinear" for SentenceBert / "linear" for Bert
  SCHEDULER: 'WarmupLinear'
  VALIDATION_SPLIT: 0.2


EVALUATION:
  # Evaluation methods - "EMBEDDINGS" / "CROSS_ENCODER" / "CLASSIFIER" / "SBERT_CROSS_ENCODER"
  EVALUATION_METHOD : "SBERT_CROSS_ENCODER"
  # Model name for evaluation - # Specify a model name which is implemented via Huggingface - "bert-base-uncased" / "models/convbert" (DialoGLUE convbert model) / "sentence-transformers/all-MiniLM-L6-v2"
  MODEL_NAME : "bert-base-uncased"
  TOKENIZER_NAME: "bert-base-uncased"
  BATCH_SIZE : 16
  # Set True/False for the evaluation metrics
  CHECK_SUCCESS_RATE: True
  CHECK_PRECISION : True
  CHECK_MAP: True
  CHECK_NDCG: True
  CHECK_MRR: True
  CHECK_F1_MACRO: True
  CHECK_F1_MICRO: True
  CHECK_F1_WEIGHTED: True
  CHECK_OOS_ACCURACY : True
  OOS_THRESHOLD : [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
  # Specify k values less than 10
  K_VAL : [1,2,3,5]

EMBEDDINGS:
  # Uses the following evaluation only if EVALUATION_METHOD = "EMBEDDINGS"
  # Set True for bm25/fastext/glove evaluation and False for dense/sparse embedding evaluation
  USE_BM25_FASTTEXT_GLOVE: False
  # Select either "BM25" / "FASTTEXT" / 'GLOVE'
  SELECT_BM25_FASTTEXT_GLOVE: "BM25"
  FASTTEXT_MODEL_PATH: "models/fasttext_ecom_model_2.bin"
  GLOVE_MODEL_PATH: "models/glove.6B/glove.6B.300d.txt"

  # Specify embedding type - dense / sparse - Used only if USE_BM25_FASTTEXT_GLOVE is set to False
  EMBEDDING_TYPE : "dense"
  # If sparse embedding is used, specify "tfidf-word"/"tfidf-char"/"cv"
  SPARSE_EMB_METHOD: "tfidf-word"
