DATASETS:
  # Source - haptik / dialoglue / cough
  DATASET_SOURCE: "haptik"
  # For Haptik - curekart / powerplay11 / sofmattress
  # For Dialogue - banking / clinc / hwu
  DATASET_NAME: "curekart"
  OOS_CLASS_NAME: "NO_NODES_DETECTED"

EMBEDDINGS:
  # Set True for bm25/fastext/glove evaluation and False for dense/sparse embedding evaluation
  USE_BM25_FASTTEXT_GLOVE: True
  # Select either "BM25" / "FASTTEXT" / 'GLOVE'
  SELECT_BM25_FASTTEXT_GLOVE: "BM25"
  FASTTEXT_MODEL_PATH: "models/fasttext_ecom_model_2.bin"
  GLOVE_MODEL_PATH: "models/glove.6B/glove.6B.300d.txt"

  # Specify embedding type - dense / sparse - Used only if USE_BM25_FASTTEXT_GLOVE is set to False
  EMBEDDING_TYPE : "sparse"
  # If sparse embedding is used, specify "tfidf-word"/"tfidf-char"/"cv"
  SPARSE_EMB_METHOD: "tfidf-word"
  # Specify a model name which is implemented via Huggingface - "bert-base-uncased" / "models/convbert" (DialoGLUE convbert model) / "sentence-transformers/all-MiniLM-L6-v2"
  MODEL_NAME : "models/convbert"


TRAINING:
  NUM_ITERATIONS : 100
  TRAIN_OUTPUT_DIR: "./models/"
  MODEL_NAME : "sentence-transformers/all-MiniLM-L6-v2"
  # Specify model layer to unfreeze - 11,5 etc
  SENTBERT_LAYERS_TO_UNFREEZE : [5]
  # Specify a loss metric for Sentence Bert models - CosineSimilarityLoss / ContrastiveLoss
  LOSS_METRIC : "ContrastiveLoss"
  BATCH_SIZE : 16
  LEARNING_RATE: 2e-5
  SCHEDULER: 'WarmupLinear'

CROSS_ENCODER_TRAINING:
  USE_CROSS_ENCODER : False
  NUM_ITERATIONS : 20000
  TRAIN_OUTPUT_DIR: "./models/"
  MODEL_NAME : "bert-base-uncased"
  TOKENIZER_NAME: "bert-base-uncased"
  # Specify model layer to unfreeze - 11,5 etc
  BERT_LAYERS_TO_UNFREEZE : 11
  BATCH_SIZE : 16
  LEARNING_RATE: 2e-5
  SCHEDULER: 'linear'

EVALUATION:
  # Set True/False for the evaluation metrics
  CHECK_SUCCESS_RATE: True
  CHECK_PRECISION : True
  CHECK_MAP: True
  CHECK_NDCG: True
  CHECK_MRR: True
  CHECK_F1_MACRO: True
  CHECK_F1_MICRO: True
  CHECK_F1_WEIGHTED: True
  CHECK_OOS_ACCURACY : True
  CROSS_ENCODER_MODEL_NAME: "./models/cross_encoder.pt"
  OOS_THRESHOLD : [0.1,0.2,0.3]
  # Specify k values less than 10
  K_VAL : [1,2,5,10]
